-- Supabase schema for Parascene (table prefix: prsn_)

CREATE TABLE IF NOT EXISTS prsn_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text UNIQUE NOT NULL,
  password_hash text NOT NULL,
  role text NOT NULL DEFAULT 'consumer',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS prsn_user_profiles (
  user_id bigint PRIMARY KEY REFERENCES prsn_users(id) ON DELETE CASCADE,
  user_name text UNIQUE,
  display_name text,
  about text,
  socials jsonb,
  avatar_url text,
  cover_image_url text,
  badges jsonb,
  meta jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS prsn_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES prsn_users(id),
  token_hash text UNIQUE NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS prsn_moderation_queue (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_type text NOT NULL,
  content_id text NOT NULL,
  status text NOT NULL,
  reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS prsn_servers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES prsn_users(id),
  name text NOT NULL,
  server_url text NOT NULL,
  auth_token text,
  status text NOT NULL,
  status_date timestamptz,
  description text,
  members_count integer NOT NULL DEFAULT 0,
  server_config jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS prsn_policy_knobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL,
  value text NOT NULL,
  description text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS prsn_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES prsn_users(id),
  role text,
  title text NOT NULL,
  message text NOT NULL,
  link text,
  created_at timestamptz NOT NULL DEFAULT now(),
  acknowledged_at timestamptz
);

CREATE TABLE IF NOT EXISTS prsn_explore_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  summary text NOT NULL,
  category text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS prsn_creations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES prsn_users(id),
  title text NOT NULL,
  body text NOT NULL,
  status text NOT NULL DEFAULT 'draft',
  created_at timestamptz NOT NULL DEFAULT now()
);


CREATE TABLE IF NOT EXISTS prsn_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  description text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS prsn_created_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES prsn_users(id),
  filename text NOT NULL,
  file_path text NOT NULL,
  width integer NOT NULL,
  height integer NOT NULL,
  color text,
  status text NOT NULL DEFAULT 'creating',
  created_at timestamptz NOT NULL DEFAULT now(),
  published boolean NOT NULL DEFAULT false,
  published_at timestamptz,
  title text,
  description text
);

CREATE TABLE IF NOT EXISTS prsn_feed_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  summary text NOT NULL,
  author text NOT NULL,
  tags text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_image_id bigint REFERENCES prsn_created_images(id)
);

CREATE TABLE IF NOT EXISTS prsn_user_credits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL UNIQUE REFERENCES prsn_users(id),
  balance double precision NOT NULL DEFAULT 0,
  last_daily_claim_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS prsn_user_follows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id bigint NOT NULL REFERENCES prsn_users(id) ON DELETE CASCADE,
  following_id bigint NOT NULL REFERENCES prsn_users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(follower_id, following_id),
  CHECK(follower_id != following_id)
);

CREATE INDEX IF NOT EXISTS prsn_user_follows_follower_id_idx
  ON prsn_user_follows(follower_id);

CREATE INDEX IF NOT EXISTS prsn_user_follows_following_id_idx
  ON prsn_user_follows(following_id);

-- Atomic credit transfer (no ledger table; balances only)
CREATE OR REPLACE FUNCTION prsn_transfer_credits(
  from_user_id bigint,
  to_user_id bigint,
  amount double precision
)
RETURNS TABLE(from_balance double precision, to_balance double precision)
LANGUAGE plpgsql
AS $$
DECLARE
  sender_balance double precision;
BEGIN
  IF from_user_id IS NULL OR to_user_id IS NULL THEN
    RAISE EXCEPTION 'from_user_id and to_user_id are required';
  END IF;

  IF from_user_id = to_user_id THEN
    RAISE EXCEPTION 'cannot tip yourself';
  END IF;

  IF amount IS NULL OR amount <= 0 OR amount <> amount THEN
    RAISE EXCEPTION 'invalid amount';
  END IF;

  -- Ensure both users have a credits row
  INSERT INTO prsn_user_credits (user_id, balance)
    VALUES (from_user_id, 0)
    ON CONFLICT (user_id) DO NOTHING;
  INSERT INTO prsn_user_credits (user_id, balance)
    VALUES (to_user_id, 0)
    ON CONFLICT (user_id) DO NOTHING;

  -- Lock sender row to prevent concurrent overdrafts
  SELECT balance
    INTO sender_balance
    FROM prsn_user_credits
    WHERE user_id = from_user_id
    FOR UPDATE;

  IF sender_balance < amount THEN
    RAISE EXCEPTION 'insufficient credits';
  END IF;

  UPDATE prsn_user_credits
    SET balance = balance - amount,
        updated_at = now()
    WHERE user_id = from_user_id;

  UPDATE prsn_user_credits
    SET balance = balance + amount,
        updated_at = now()
    WHERE user_id = to_user_id;

  RETURN QUERY
    SELECT
      (SELECT balance FROM prsn_user_credits WHERE user_id = from_user_id),
      (SELECT balance FROM prsn_user_credits WHERE user_id = to_user_id);
END;
$$;

CREATE TABLE IF NOT EXISTS prsn_likes_created_image (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES prsn_users(id),
  created_image_id bigint NOT NULL REFERENCES prsn_created_images(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id, created_image_id)
);

CREATE OR REPLACE VIEW prsn_created_image_like_counts
  WITH (security_invoker = true) AS
  SELECT
    created_image_id,
    COUNT(*)::bigint AS like_count
  FROM prsn_likes_created_image
  GROUP BY created_image_id;

CREATE TABLE IF NOT EXISTS prsn_comments_created_image (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES prsn_users(id),
  created_image_id bigint NOT NULL REFERENCES prsn_created_images(id),
  text text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS prsn_comments_created_image_created_image_id_created_at_idx
  ON prsn_comments_created_image (created_image_id, created_at);

CREATE INDEX IF NOT EXISTS prsn_comments_created_image_user_id_idx
  ON prsn_comments_created_image (user_id);

CREATE OR REPLACE VIEW prsn_created_image_comment_counts
  WITH (security_invoker = true) AS
  SELECT
    created_image_id,
    COUNT(*)::bigint AS comment_count
  FROM prsn_comments_created_image
  GROUP BY created_image_id;

-- Row Level Security and Comments

ALTER TABLE prsn_users ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_users IS 'Parascene: user accounts with authentication credentials and roles. RLS enabled without policies - only service role can access. All access controlled via API layer.';

ALTER TABLE prsn_sessions ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_sessions IS 'Parascene: user session tokens for authentication. RLS enabled without policies - only service role can access. All access controlled via API layer.';

ALTER TABLE prsn_moderation_queue ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_moderation_queue IS 'Parascene: content moderation queue for reviewing user-generated content. RLS enabled without policies - only service role can access. All access controlled via API layer.';

ALTER TABLE prsn_servers ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_servers IS 'Parascene: consolidated provider servers table combining registry, status, and community server information. RLS enabled without policies - only service role can access. All access controlled via API layer.';

ALTER TABLE prsn_policy_knobs ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_policy_knobs IS 'Parascene: system configuration and policy settings. RLS enabled without policies - only service role can access. All access controlled via API layer.';

ALTER TABLE prsn_notifications ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_notifications IS 'Parascene: user notifications, can be scoped by user_id or role. RLS enabled without policies - only service role can access. All access controlled via API layer.';

ALTER TABLE prsn_explore_items ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_explore_items IS 'Parascene: featured content items for the explore/discovery page. RLS enabled without policies - only service role can access. All access controlled via API layer.';

ALTER TABLE prsn_creations ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_creations IS 'Parascene: user-created content and artifacts. RLS enabled without policies - only service role can access. All access controlled via API layer.';


ALTER TABLE prsn_templates ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_templates IS 'Parascene: content templates available to users. RLS enabled without policies - only service role can access. All access controlled via API layer.';

ALTER TABLE prsn_created_images ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_created_images IS 'Parascene: user-generated images with metadata and publication status. RLS enabled without policies - only service role can access. All access controlled via API layer.';

ALTER TABLE prsn_feed_items ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_feed_items IS 'Parascene: feed items for the main content feed, can reference created images. RLS enabled without policies - only service role can access. All access controlled via API layer.';

ALTER TABLE prsn_user_credits ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_user_credits IS 'Parascene: user credit balances and daily claim tracking. RLS enabled without policies - only service role can access. All access controlled via API layer.';

ALTER TABLE prsn_user_follows ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_user_follows IS 'Parascene: user follow relationships. RLS enabled without policies - only service role can access. All access controlled via API layer.';

ALTER TABLE prsn_likes_created_image ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_likes_created_image IS 'Parascene: user likes on created images. RLS enabled without policies - only service role can access. All access controlled via API layer.';

ALTER TABLE prsn_comments_created_image ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_comments_created_image IS 'Parascene: user comments on created images. RLS enabled without policies - only service role can access. All access controlled via API layer.';

ALTER TABLE prsn_user_profiles ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE prsn_user_profiles IS 'Parascene: public profile fields (username, display name, bio, socials, avatar/cover URLs, badges, meta). RLS enabled without policies - only service role can access. All access controlled via API layer.';

-- Views with RLS policies
COMMENT ON VIEW prsn_created_image_like_counts IS 'Parascene: aggregated like counts per created image. RLS enabled with restrictive policy - only service role can access. All access controlled via API layer.';

COMMENT ON VIEW prsn_created_image_comment_counts IS 'Parascene: aggregated comment counts per created image. RLS enabled with restrictive policy - only service role can access. All access controlled via API layer.';

-- Create restrictive RLS policies on views (service role bypasses RLS)
CREATE POLICY "Service role only - like counts" ON prsn_created_image_like_counts
  FOR ALL
  USING (false)
  WITH CHECK (false);

CREATE POLICY "Service role only - comment counts" ON prsn_created_image_comment_counts
  FOR ALL
  USING (false)
  WITH CHECK (false);
